/*
 * Album Store API
 *
 * CS6650 Fall 2023
 *
 * API version: 1.0.0
 * Contact: i.gorton@northeasern.edu
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "example.com/router"
)

func main() {
<<<<<<< HEAD
	log.Printf("Server started")

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))

	//log.Fatal(http.ListenAndServe("localhost:8080", router))
=======
	// log.Printf("Server started")

	router := sw.NewRouter()
	print("HelloWord")

	log.Fatal(http.ListenAndServe("localhost:8080", router))
>>>>>>> 1ff6e0005fbb7ef6c233e98204b0952d67d8f157
}
