/*
 * Album Store API
 *
 * CS6650 Fall 2023
 *
 * API version: 1.0.0
 * Contact: i.gorton@northeasern.edu
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
<<<<<<< HEAD
		"/AlbumStore/1.0.0/",
=======
		"/IGORTON/AlbumStore/1.0.0/",
>>>>>>> 1ff6e0005fbb7ef6c233e98204b0952d67d8f157
		Index,
	},

	Route{
		"GetAlbumByKey",
		strings.ToUpper("Get"),
<<<<<<< HEAD
		"/AlbumStore/1.0.0/albums/{albumID}",
=======
		"/IGORTON/AlbumStore/1.0.0/albums/{albumID}",
>>>>>>> 1ff6e0005fbb7ef6c233e98204b0952d67d8f157
		GetAlbumByKey,
	},

	Route{
		"NewAlbum",
		strings.ToUpper("Post"),
<<<<<<< HEAD
		"/AlbumStore/1.0.0/albums",
=======
		"/IGORTON/AlbumStore/1.0.0/albums",
>>>>>>> 1ff6e0005fbb7ef6c233e98204b0952d67d8f157
		NewAlbum,
	},
}
